# Generated by Django 4.2.26 on 2025-11-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
