# Generated by Django 4.2.26 on 2025-11-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorderline'),
        ),
    ]
