# Generated by Django 4.2.26 on 2025-11-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_goodsreceipt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
