# Generated by Django 4.2.26 on 2025-11-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_alter_goodsreceiptline_expiry_date'),
        ('warehouses', '0002_alter_productbatch_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='goods_receipt_line',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_line', to='purchasing.goodsreceiptline'),
            preserve_default=False,
        ),
    ]
