# Generated by Django 4.2.26 on 2025-11-16 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_alter_goodsreceiptline_expiry_date'),
        ('warehouses', '0004_alter_productbatch_goods_receipt_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='goods_receipt_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='purchasing.goodsreceiptline'),
        ),
    ]
