# Generated by Django 4.2.26 on 2025-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_alter_unitofmeasure_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='short_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
